project_id = "kpnngvzswjgulmvgsbrn"

[functions.send-notification]
verify_jwt = false

[functions.notify-access-request]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.landing-lead]
verify_jwt = false
